### ISSUE TITLE
gitlab getRemoteTag() fails to return a tag

### ISSUE THREAD

**Issue by franceimage** [franceimage/wp-alt-repositories#11]

**Comment by afragen** [comment]
The API endpoint requires the project ID.

The correct URI is something like the following.

`https://gitlab.com/api/v3/projects/$project->ID/repositories/tags?private_token=...`

From there you will return an array of tags to sort for the one you want.

The URI for downloading a tagged repository is as follows.

`https://gitlab.com/<owner>/<repo>/repository/archive.zip?ref=$tag`

Finding and constructing the branch is similar. I happened to be working on this last evening. :wink:

**Comment by franceimage** [comment]
Thanks for you input.

I just found my problem: even if you are accessing a public repository, you need to use an authenticated connection to use gitlab API.

So, for the records, this code works:

_$url = 'http://gitlab.com/api/v3/projects/' . urlencode($repository) . '/repository/tags';_

where $repository is owner/repo

And it's as well because it is quite a chore to get the ID of the project when you have a repo name

**Comment by afragen** [comment]
FWIW, I wrote a inc little function to find that.

https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/GitLab_API.php#L369-L392

Interestingly I didn't see in the documentation where the project ID and the owner/repo were interchangeable.

**Comment by afragen** [comment]
> Get a specific project, identified by project ID or NAMESPACE/PROJECT_NAME, which is owned by the authenticated user. If using namespaced projects call make sure that the NAMESPACE/PROJECT_NAME is URL-encoded, eg. /api/v3/projects/diaspora%2Fdiaspora (where / is represented by %2F).

This would seem to indicate it will work only if you are the owner, whereas ere seem to be no such limitations on the project ID. I don't know.

**Comment by franceimage** [comment]
It's not limited to owned repositories. I created a 2nd user in gitlab.com and my first user can use NAMESPACE/PROJECT_NAME naming in API calls to check on the 2nd user's projects.

Did you test if you need to authenticate when you use project ID ?

**Comment by afragen** [comment]
I think you need to use `?private_token=...` with almost everything except downloading within the API.
