### ISSUE TITLE
Plugin update not immediately available in plugin admin panel

### ISSUE THREAD

**Issue by franceimage** [franceimage/wp-alt-repositories#7]
To reproduce
* Click *check for updates* or *update plugin definition*
* Update available: you can go to the Plugins Admin Panel
* On admin panel, there is no update available until you refresh the panel a few times

**Comment by afragen** [comment]
I can't explain this either, but I see it.

**Comment by franceimage** [comment]
Do you notice it only for plugins and not for themes ?

**Comment by afragen** [comment]
I noticed it on both.

**Comment by franceimage** [comment]
Fixed by giving a link to update action  instead of a link to plugin/theme admin panel.
